language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: MmwDTh7AAe5EvtZ+YPn3olMyMvrrz+NKT/mwzaw8FT9RVjX+Q7UiWF/8AjxZzHW7HZ2w5HoeNxGe98xwzijbuJPdR1T++m40KG2wIf47Sz9rKQSiARtgk4XHu/Qu0XN/mmVFnrQvBdAUczf+yVDt7fYyIXFuGBAgZBCLRUIKYFTx4+XMoir9vybcoGfpg0Mr0VYq1/bJKO75rUikGgUWqpvCAot7CeQlOTrZGMp744GVHxaa6ZOgLDH/EW9ND0YJhbdUzSMU9YukDva/YDVwh7ALu1kV4zvx3P0iPhBq6o/EDY09lCf5YbdSEkgLUmsWvDWCixJ+WqsCzmElnlbTKqnZHGZoUJc1Gxaemh3s3XfXnu6cgJgNRo/DzDHmSOUCqNfDGRI6DKCdZs6bNzeX9v/1HAbKcCa3uHOyT6YH79sZkM6FPH1T5WgqLqVa4Fsyxqq0y247NvSem1XPSyTY/eH+uSUXJm5TlXpuRUkyIOoYY8FfwoRhKqcWnIyF4BLv8xcV0IY200n/JA8XRYesI7BF4yBAmIargg0ABDKcw95ZO2e4lsTy9T8Fxo2nA5QGPnCWv6wJg2o9b7gN6oHqXkNF1bEpXPr+Ux5b+BT/+ZssLCZqG59zSyX99KrPTDhxPR2RAc5Grh8iRf9ArKokAo1zBRSaYc8FTgw5ZMl/eks=
  app: node-shopping-list-integration-tests enigmatic-bayou-40668
  on:
    repo: joshhrycek/node-shopping-list-integration-tests
